### ISSUE TITLE
I can't install using pip "ModuleNotFoundError: No module named 'gsl_site'"

### ISSUE THREAD

**Issue by diegourreamendez** [pygsl/pygsl#19]
`Traceback (most recent call last):
  File "E:\pygsl-2.3.3\gsl_dist\gsl_Location.py", line 141, in __init__
    import gsl_site
ModuleNotFoundError: No module named 'gsl_site'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\pygsl-2.3.3\setup.py", line 99, in <module>
    from gsl_Extension import gsl_Extension
  File "E:\pygsl-2.3.3\gsl_dist\gsl_Extension.py", line 22, in <module>
    from gsl_Location import gsl_Location
  File "E:\pygsl-2.3.3\gsl_dist\gsl_Location.py", line 160, in <module>
    gsl_Location = _gsl_Location_file()
  File "E:\pygsl-2.3.3\gsl_dist\gsl_Location.py", line 148, in __init__
    raise DistutilsExecError(msg % des)
distutils.errors.DistutilsExecError: I do not know how to run gsl-config
on this system. Therefore you must provide me with the information
where to find the GSL library. I could not import `gsl_site'.
Reason: No module named 'gsl_site'. Copy gsl_site_example.py to gsl_site.py.
Edit the variables in that file to reflect your installation.

(rcop) E:\pygsl-2.3.3>python setup.py install
Traceback (most recent call last):
  File "E:\pygsl-2.3.3\gsl_dist\gsl_Location.py", line 141, in __init__
    import gsl_site
ModuleNotFoundError: No module named 'gsl_site'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\pygsl-2.3.3\setup.py", line 99, in <module>
    from gsl_Extension import gsl_Extension
  File "E:\pygsl-2.3.3\gsl_dist\gsl_Extension.py", line 22, in <module>
    from gsl_Location import gsl_Location
  File "E:\pygsl-2.3.3\gsl_dist\gsl_Location.py", line 160, in <module>
    gsl_Location = _gsl_Location_file()
  File "E:\pygsl-2.3.3\gsl_dist\gsl_Location.py", line 148, in __init__
    raise DistutilsExecError(msg % des)
distutils.errors.DistutilsExecError: I do not know how to run gsl-config
on this system. Therefore you must provide me with the information
where to find the GSL library. I could not import `gsl_site'.
Reason: No module named 'gsl_site'. Copy gsl_site_example.py to gsl_site.py.
Edit the variables in that file to reflect your installation.`

**Comment by PierreSchnizer** [comment]
I guess (as much as the setup script) that your are trying to build pygsl on a windows box.

On posix systems pygsl runs GSL's gsl-config script to obtain the information where gsl is installed. 

On windows there is no shell and thus this script is not available. Therefore you need to  "Copy gsl_site_example.py to gsl_site.py. Edit the variables in that file to reflect your installation" (that's what the script tried to tell you).

Please note, that you need to have GSL built on windows. In my experience that was not that trivial.I have not built pygsl on windows for the last years. Don't hesitate to ask if you need help on this subject.

Have look to the scripts provided at  https://github.com/pygsl/pygsl/blob/main/doc/ref/install.rst#building-on-win32 or https://github.com/pygsl/pygsl/tree/main/doc/win

If you built it successfully, please  consider sharing your lessons learned , what was required to build pygsl on windows

**Comment by PierreSchnizer** [comment]
Just to clarify: pip install on windows would require a binary wheel upstream.

**Comment by diegourreamendez** [comment]
Since I am a Windows user, I cannot use install the package successfully, however with UBUNTU I was able to install the package using Linux. Thanks for your help!!
