### ISSUE TITLE
pygsl no longer compiles with python3.12

### ISSUE THREAD

**Issue by Kadelka** [pygsl/pygsl#25]
I tried to compile pygsl with python3.12 and got
python312 setup.py build
Traceback (most recent call last):
  File "/giga/install/python312/pygsl-2.3.3/setup.py", line 99, in <module>
    from gsl_Extension import gsl_Extension
  File "/giga/install/python312/pygsl-2.3.3/gsl_dist/gsl_Extension.py", line 19, in <module>
    import imp
ModuleNotFoundError: No module named 'imp'

After depreciating the modul imp.py has been removed in python3.12

Will there be any new version of pygsl? It's very useful.

**Comment by Kadelka** [comment]
The following solution solved my problem:

In gsl_dist/gsl_Extension.py change line 19:
replace import imp by import importlib
and in line 112:
imp.find_module("Numeric") by importlib.util.find_spec("Numeric")

(see f.i. https://stackoverflow.com/questions/43964166/imp-module-is-deprecated-in-favour-of-importlib)

**Comment by clinssen** [comment]
Thank you for the report and suggested fix!
