### ISSUE TITLE
Fix pip/PyPI install

### ISSUE THREAD

**Issue by clinssen** [pygsl/pygsl#3]
Newer versions of pip cannot install [the latest pygsl from PyPI](https://pypi.org/project/pygsl/), because the version number in the package metadata (in https://github.com/pygsl/pygsl/blob/1430c11f64100064f7a85e8e67e273d5bcbf2441/setup.cfg#L17) is inconsistent with the filename (``pygsl-2.3.0.1.tar.gz``). The fourth digit is not as prescribed by the "semantic versioning" system, so perhaps we should take this opportunity to remove it altogether, and do a new release with version number 2.3.1. This should solve the pip install issue.

The error message from pip is:

WARNING: Discarding https://files.pythonhosted.org/packages/17/fc/9c11163f017a0d6877141d4d4edb619b0f05990d865caab840a2d0463581/pygsl-2.3.0.1.tar.gz#sha256=b248a899a9df0b94996fd5fe070f8ecbd3d42ca07486a829dedcdfdd70a3337d (from https://pypi.org/simple/pygsl/). Requested pygsl from file:///home/clinssen/.cache/pip/wheels/4b/d0/ab/9f52c8f2cc5f2a785992894d4be820e6223cadbd70c1496862/pygsl-2.3.0-cp35-cp35m-linux_x86_64.whl has different version in metadata: '2.3.0'

**Comment by PierreSchnizer** [comment]
Pushed version to 2.3.1
Tagged repo
