### ISSUE TITLE
Remove dependency on `numpy.distutils` since it is deprecated and it will be removed from numpy

### ISSUE THREAD

**Issue by jose-matos** [pygsl/pygsl#36]
The work being done here is in order to prepare for Python 3.13 in Fedora.

https://numpy.org/doc/stable/reference/distutils_status_migration.html#distutils-status-migration

There is a failure in Fedora 40 due to 
```
+ /usr/bin/python3 setup.py gsl_wrappers
/builddir/build/BUILD/pygsl-2.3.3/gsl_dist/gsl_Location.py:63: SyntaxWarning: invalid escape sequence '\.'
  return re.split('\.',version)
Traceback (most recent call last):
  File "/builddir/build/BUILD/pygsl-2.3.3/gsl_dist/gsl_Extension.py", line 25, in <module>
    from array_includes import array_include_dirs
  File "/builddir/build/BUILD/pygsl-2.3.3/gsl_dist/array_includes.py", line 7, in <module>
    from numpy.distutils.misc_util import get_numpy_include_dirs
ModuleNotFoundError: No module named 'numpy.distutils'
```
https://numpy.org/doc/stable/reference/distutils_status_migration.html#distutils-status-migration

This can be easily solved since pygsl only uses a single call that has a direct equivalent in `numpy`:
```
-array_include_dirs = []
-from numpy.distutils.misc_util import get_numpy_include_dirs
-array_include_dirs = get_numpy_include_dirs()
+import numpy
+array_include_dirs = [ numpy.get_include() ]
```

**Comment by PierreSchnizer** [comment]
Thanks for the report!
I will fix it

**Comment by PierreSchnizer** [comment]
https://github.com/pygsl/pygsl/tree/dev/feature/ci-python-matrix should include the fix.

Could you check please?

**Comment by jose-matos** [comment]
Yes, this works for this case.
Thank you. :smile:
