### ISSUE TITLE
siman.py invalid import

### ISSUE THREAD

**Issue by Thomas-Z** [pygsl/pygsl#43]
Hi,

I think a problem was introduced [in this commit.](https://github.com/pygsl/pygsl/commit/796959e9ad2dc39e7e94ccbfcb3ba9a2d9b6fe48#diff-4caae16cfac2c06a976b1647514f1082c5146a6d69385684cc1344e457faec42).

```python
from abc import abstractmethod, abcmeta
``` 

`abcmeta` does not exist and I'm guessing it should be replaced by `ABCMeta`.

Thanks !

**Comment by PierreSchnizer** [comment]
Fix in https://github.com/pygsl/pygsl/pull/44

**Comment by PierreSchnizer** [comment]
Merged into main
