### ISSUE TITLE
Multinomial Example

### ISSUE THREAD

**Issue by selmys** [pygsl/pygsl#47]
For some reason this example doesn't work for me.

Python 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pygsl import rng
>>> r = rng.mt19937_1998()
>>> phi = (0.2,0.2,0.2,0.4)
>>> k = 5
>>> n = r.multinomial(phi, k, 10)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: object of too small depth for desired array
>>>

Being new to using this library I'd appreciate any help.

**Comment by PierreSchnizer** [comment]
Its a bug. Thanks for reporting. Pierre

**Comment by selmys** [comment]
Thanks for the quick fix.
Much appreciated.
